# Generated by Django 3.0.2 on 2020-01-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialScamEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('designated_scam', models.BooleanField(default=False)),
                ('number_encountered', models.IntegerField(default=0)),
            ],
        ),
    ]
