# Generated by Django 3.0.2 on 2020-01-12 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataservice', '0002_knownspamemails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KnownSpamEmails',
            new_name='KnownScamEmails',
        ),
    ]
