# Generated by Django 3.0.2 on 2020-01-12 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservice', '0003_auto_20200111_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownscamemails',
            name='first_updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 1, 12, 1, 29, 41, 816807)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potentialscamemail',
            name='first_updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 1, 12, 1, 30, 0, 369016)),
            preserve_default=False,
        ),
    ]
